"""JWT Authentication for Meridian API.

Provides JWT-based authentication for REST API endpoints.
Implements access tokens and refresh tokens for secure API access.

Usage:
    from src.api.auth import create_access_token, get_current_user
    
    @app.post("/login")
    async def login(credentials: LoginRequest):
        user = authenticate_user(credentials)
        token = create_access_token({"sub": user.id})
        return {"access_token": token}
    
    @app.get("/protected")
    async def protected_route(current_user: User = Depends(get_current_user)):
        return {"message": f"Hello {current_user.username}"}
"""

import os
from datetime import datetime, timedelta
from typing import Dict, Optional, Any

import structlog
from jose import JWTError, jwt
from passlib.context import CryptContext

logger = structlog.get_logger(__name__)

# Configuration
# In production (ENVIRONMENT=production) JWT_SECRET_KEY MUST be set.
# In dev/test, a clearly-marked dev key is generated at import-time only if absent.
_ENV = os.getenv("ENVIRONMENT", "development").lower()
_SECRET_FROM_ENV = os.getenv("JWT_SECRET_KEY")

if not _SECRET_FROM_ENV:
    if _ENV == "production":
        raise RuntimeError(
            "JWT_SECRET_KEY environment variable is required in production. "
            "Generate one with: python -c 'import secrets; print(secrets.token_urlsafe(64))'"
        )
    # Dev-only fallback — not committed/known, regenerated each process start.
    import secrets as _secrets
    _SECRET_FROM_ENV = _secrets.token_urlsafe(64)
    logger.warning(
        "jwt_secret_autogenerated",
        message="JWT_SECRET_KEY not set; generated ephemeral dev key. "
                "Set JWT_SECRET_KEY in .env for stable tokens across restarts.",
    )

SECRET_KEY = _SECRET_FROM_ENV
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = int(os.getenv("JWT_ACCESS_TOKEN_EXPIRE_MINUTES", "30"))
REFRESH_TOKEN_EXPIRE_DAYS = int(os.getenv("JWT_REFRESH_TOKEN_EXPIRE_DAYS", "7"))

# Password hashing
pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")


class TokenData:
    """Data extracted from JWT token."""
    
    def __init__(self, user_id: str, username: str, scopes: list = None):
        self.user_id = user_id
        self.username = username
        self.scopes = scopes or []


def verify_password(plain_password: str, hashed_password: str) -> bool:
    """Verify a password against a hash."""
    return pwd_context.verify(plain_password, hashed_password)


def get_password_hash(password: str) -> str:
    """Generate password hash."""
    return pwd_context.hash(password)


def create_access_token(
    data: Dict[str, Any],
    expires_delta: Optional[timedelta] = None
) -> str:
    """Create JWT access token.
    
    Args:
        data: Payload data (must include 'sub' for subject/user_id)
        expires_delta: Optional custom expiration time
        
    Returns:
        JWT token string
    """
    to_encode = data.copy()
    
    if expires_delta:
        expire = datetime.utcnow() + expires_delta
    else:
        expire = datetime.utcnow() + timedelta(minutes=ACCESS_TOKEN_EXPIRE_MINUTES)
    
    to_encode.update({
        "exp": expire,
        "iat": datetime.utcnow(),
        "type": "access"
    })
    
    encoded_jwt = jwt.encode(to_encode, SECRET_KEY, algorithm=ALGORITHM)
    
    logger.info(
        "access_token_created",
        user_id=data.get("sub"),
        expires=expire.isoformat()
    )
    
    return encoded_jwt


def create_refresh_token(user_id: str) -> str:
    """Create JWT refresh token.
    
    Refresh tokens have longer expiration and are used
    to obtain new access tokens without re-authenticating.
    
    Args:
        user_id: User identifier
        
    Returns:
        JWT refresh token string
    """
    expire = datetime.utcnow() + timedelta(days=REFRESH_TOKEN_EXPIRE_DAYS)
    
    data = {
        "sub": user_id,
        "exp": expire,
        "iat": datetime.utcnow(),
        "type": "refresh"
    }
    
    encoded_jwt = jwt.encode(data, SECRET_KEY, algorithm=ALGORITHM)
    
    logger.info(
        "refresh_token_created",
        user_id=user_id,
        expires=expire.isoformat()
    )
    
    return encoded_jwt


def decode_token(token: str) -> Optional[Dict[str, Any]]:
    """Decode and validate JWT token.
    
    Args:
        token: JWT token string
        
    Returns:
        Decoded payload or None if invalid
    """
    try:
        payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
        return payload
    except JWTError as e:
        logger.warning("token_decode_failed", error=str(e))
        return None


def get_token_data(token: str) -> Optional[TokenData]:
    """Extract token data from JWT.
    
    Args:
        token: JWT token string
        
    Returns:
        TokenData object or None if invalid
    """
    payload = decode_token(token)
    
    if payload is None:
        return None
    
    user_id = payload.get("sub")
    username = payload.get("username", "")
    scopes = payload.get("scopes", [])
    
    if user_id is None:
        return None
    
    return TokenData(user_id=user_id, username=username, scopes=scopes)


def verify_token_type(token: str, expected_type: str) -> bool:
    """Verify token is of expected type (access/refresh).
    
    Args:
        token: JWT token string
        expected_type: Expected token type
        
    Returns:
        True if token type matches
    """
    payload = decode_token(token)
    
    if payload is None:
        return False
    
    token_type = payload.get("type", "access")
    return token_type == expected_type


# In-memory user store seeded from environment variables.
# Production deployments should replace this with a real user database
# (PostgreSQL + SQLAlchemy / OAuth2 provider / IdP integration).
#
# Required env vars to enable bootstrap users (otherwise users dict is empty):
#   MERIDIAN_ADMIN_USERNAME, MERIDIAN_ADMIN_PASSWORD
#   MERIDIAN_VIEWER_USERNAME, MERIDIAN_VIEWER_PASSWORD
def _build_users_db() -> Dict[str, Dict[str, Any]]:
    users: Dict[str, Dict[str, Any]] = {}

    admin_user = os.getenv("MERIDIAN_ADMIN_USERNAME")
    admin_pw = os.getenv("MERIDIAN_ADMIN_PASSWORD")
    if admin_user and admin_pw:
        users[admin_user] = {
            "user_id": os.getenv("MERIDIAN_ADMIN_USER_ID", "user-admin-001"),
            "hashed_password": get_password_hash(admin_pw),
            "scopes": ["read", "write", "admin"],
        }

    viewer_user = os.getenv("MERIDIAN_VIEWER_USERNAME")
    viewer_pw = os.getenv("MERIDIAN_VIEWER_PASSWORD")
    if viewer_user and viewer_pw:
        users[viewer_user] = {
            "user_id": os.getenv("MERIDIAN_VIEWER_USER_ID", "user-viewer-001"),
            "hashed_password": get_password_hash(viewer_pw),
            "scopes": ["read"],
        }

    if not users and _ENV == "production":
        raise RuntimeError(
            "No users configured. Set MERIDIAN_ADMIN_USERNAME / MERIDIAN_ADMIN_PASSWORD "
            "(and optionally viewer credentials) before starting in production."
        )

    if not users:
        logger.warning(
            "no_bootstrap_users_configured",
            message="No users defined via env vars; /auth/login will reject all requests.",
        )

    return users


_USERS_DB: Optional[Dict[str, Dict[str, Any]]] = None


def get_users_db() -> Dict[str, Dict[str, Any]]:
    """Return bootstrap user store (lazy init so tests can set env first)."""
    global _USERS_DB
    if _USERS_DB is None:
        _USERS_DB = _build_users_db()
    return _USERS_DB


def authenticate_user(username: str, password: str) -> Optional[Dict[str, Any]]:
    """Authenticate user credentials.
    
    Args:
        username: Username
        password: Plain text password
        
    Returns:
        User dict if authenticated, None otherwise
    """
    user = get_users_db().get(username)
    
    if not user:
        return None
    
    if not verify_password(password, user["hashed_password"]):
        return None
    
    logger.info("user_authenticated", username=username, user_id=user["user_id"])
    
    return {
        "user_id": user["user_id"],
        "username": username,
        "scopes": user["scopes"]
    }


def get_user_by_id(user_id: str) -> Optional[Dict[str, Any]]:
    """Get user by ID.
    
    Args:
        user_id: User identifier
        
    Returns:
        User dict or None
    """
    for username, user_data in get_users_db().items():
        if user_data["user_id"] == user_id:
            return {
                "user_id": user_data["user_id"],
                "username": username,
                "scopes": user_data["scopes"]
            }
    return None


def require_scope(token: str, required_scope: str) -> bool:
    """Check if token has required scope.
    
    Args:
        token: JWT token
        required_scope: Required permission scope
        
    Returns:
        True if token has scope
    """
    token_data = get_token_data(token)
    
    if token_data is None:
        return False
    
    return required_scope in token_data.scopes


# FastAPI dependency functions
from fastapi import Depends, HTTPException, status
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials

security = HTTPBearer()


def get_current_user(credentials: HTTPAuthorizationCredentials = Depends(security)) -> TokenData:
    """FastAPI dependency to get current user from JWT token.
    
    Usage:
        @app.get("/protected")
        async def protected_route(current_user: TokenData = Depends(get_current_user)):
            return {"user_id": current_user.user_id}
    """
    token = credentials.credentials
    
    token_data = get_token_data(token)
    
    if token_data is None:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid authentication credentials",
            headers={"WWW-Authenticate": "Bearer"},
        )
    
    return token_data


def get_current_active_user(
    current_user: TokenData = Depends(get_current_user)
) -> TokenData:
    """Get current user and verify they are active."""
    # In production, check if user is active/banned/etc
    return current_user


def require_scope_dependency(required_scope: str):
    """Create FastAPI dependency that requires specific scope.
    
    Usage:
        @app.post("/admin-only")
        async def admin_route(
            current_user: TokenData = Depends(require_scope_dependency("admin"))
        ):
            return {"message": "Admin access granted"}
    """
    def scope_checker(
        credentials: HTTPAuthorizationCredentials = Depends(security)
    ) -> TokenData:
        token = credentials.credentials
        
        if not require_scope(token, required_scope):
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail=f"Insufficient permissions. Scope '{required_scope}' required."
            )
        
        return get_token_data(token)
    
    return scope_checker


# Token refresh
async def refresh_access_token(refresh_token: str) -> Optional[Dict[str, str]]:
    """Generate new access token using refresh token.
    
    Args:
        refresh_token: Valid refresh token
        
    Returns:
        Dict with new access_token and refresh_token or None
    """
    # Verify it's a refresh token
    if not verify_token_type(refresh_token, "refresh"):
        return None
    
    token_data = get_token_data(refresh_token)
    
    if token_data is None:
        return None
    
    # Get user to include scopes
    user = get_user_by_id(token_data.user_id)
    
    if user is None:
        return None
    
    # Create new tokens
    new_access = create_access_token({
        "sub": token_data.user_id,
        "username": user["username"],
        "scopes": user["scopes"]
    })
    
    new_refresh = create_refresh_token(token_data.user_id)
    
    logger.info("tokens_refreshed", user_id=token_data.user_id)
    
    return {
        "access_token": new_access,
        "refresh_token": new_refresh,
        "token_type": "bearer"
    }


# Auth endpoints to add to main.py
def create_auth_endpoints(app):
    """Add authentication endpoints to FastAPI app.
    
    Usage:
        from src.api.auth.jwt import create_auth_endpoints
        create_auth_endpoints(app)
    """
    from fastapi import Form
    from pydantic import BaseModel
    
    class TokenResponse(BaseModel):
        access_token: str
        refresh_token: str
        token_type: str
        expires_in: int
    
    @app.post("/auth/login", response_model=TokenResponse)
    async def login(
        username: str = Form(...),
        password: str = Form(...)
    ):
        """Login and obtain JWT tokens."""
        user = authenticate_user(username, password)
        
        if not user:
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="Incorrect username or password",
                headers={"WWW-Authenticate": "Bearer"},
            )
        
        access_token = create_access_token({
            "sub": user["user_id"],
            "username": user["username"],
            "scopes": user["scopes"]
        })
        
        refresh_token = create_refresh_token(user["user_id"])
        
        return {
            "access_token": access_token,
            "refresh_token": refresh_token,
            "token_type": "bearer",
            "expires_in": ACCESS_TOKEN_EXPIRE_MINUTES * 60
        }
    
    @app.post("/auth/refresh", response_model=TokenResponse)
    async def refresh_token_endpoint(refresh_token: str = Form(...)):
        """Refresh access token."""
        result = await refresh_access_token(refresh_token)
        
        if not result:
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="Invalid refresh token"
            )
        
        return {
            **result,
            "expires_in": ACCESS_TOKEN_EXPIRE_MINUTES * 60
        }
    
    @app.get("/auth/me")
    async def get_current_user_info(
        current_user: TokenData = Depends(get_current_user)
    ):
        """Get current user info."""
        return {
            "user_id": current_user.user_id,
            "username": current_user.username,
            "scopes": current_user.scopes
        }
    
    logger.info("auth_endpoints_created")
